### ISSUE TITLE
segmentation violation on gocv.MedianBlur

### ISSUE THREAD

**Issue by pioz** [hybridgroup/gocv#533]
I get a segmentation violation when calling `gocv.MedianBlur`

## Steps to Reproduce
```go
package main

import (
	"os"
	"gocv.io/x/gocv"
)

func main() {
	filename := os.Args[1]
	matColor := gocv.IMRead(filename, gocv.IMReadColor)
	defer matColor.Close()
	matBlurred := gocv.NewMat()
	defer matBlurred.Close()
	gocv.MedianBlur(matColor, &matBlurred, 3)
	gocv.IMWrite("outBlurred.jpg", matBlurred)
}
```
Run the program with the command:
`go run medianblur.go sample.jpg`

Output:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x843f476]

runtime stack:
runtime.throw(0x40dd00f, 0x2a)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall]:
runtime.cgocall(0x408eb00, 0xc000052e28, 0xc000000180)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/cgocall.go:128 +0x5b fp=0xc000052df8 sp=0xc000052dc0 pc=0x400580b
gocv.io/x/gocv._Cfunc_MedianBlur(0x21322260, 0x213222c0, 0x3)
	_cgo_gotypes.go:4367 +0x45 fp=0xc000052e28 sp=0xc000052df8 pc=0x408a1e5
gocv.io/x/gocv.MedianBlur.func1(0x21322260, 0xc000052f48, 0x3)
	/Users/pioz/Code/go/src/gocv.io/x/gocv/imgproc.go:873 +0xa5 fp=0xc000052e68 sp=0xc000052e28 pc=0x408a8c5
gocv.io/x/gocv.MedianBlur(0x21322260, 0xc000052f48, 0x3)
	/Users/pioz/Code/go/src/gocv.io/x/gocv/imgproc.go:873 +0x3f fp=0xc000052e90 sp=0xc000052e68 pc=0x408a53f
main.main()
	/Users/pioz/Desktop/medianblur.go:14 +0x11b fp=0xc000052f60 sp=0xc000052e90 pc=0x408aaeb
runtime.main()
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/proc.go:203 +0x21e fp=0xc000052fe0 sp=0xc000052f60 pc=0x402dcce
runtime.goexit()
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x4056171
exit status 2
```

## Your Environment
```
$ cd $GOPATH/src/gocv.io/x/gocv
$ go run ./cmd/version/main.go
gocv version: 0.21.0
opencv lib version: 4.1.2
```
* Operating System and version: Mac OS X Catalina 10.15
* OpenCV version used: 4.1.2
* How did you install OpenCV? `brew install opencv`
* GoCV version used: 0.21.0
* Go version: 1.13.1
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by deadprogram** [comment]
If the unit test passes, make sure that you are not getting an empty `Mat` returned by `IMRead()` which is what happens if the file cannot be loaded.

Looking at the most current docs https://docs.opencv.org/master/d4/d86/group__imgproc__filter.html#ga564869aa33e58769b4469101aac458f9

I see this about ksize param:
>aperture linear size; it must be odd and greater than 1, for example: 3, 5, 7 ...

That indicates that the unit test here is invalid, since it uses a `ksize` of 1. I changed the unit test and ran on my local machine, and the test still passed with the test image.

I just pushed a commit that modifies the test to use a more correct param. Perhaps you can try the latest `dev` branch and the same substitution of your test image into the unit tests to see if they still pass for you.

**Comment by pioz** [comment]
I've added the follow lines but I get the same segmentation violation:
```go
if matColor.Empty() {
  panic("Mat is empty!")
}
```
I've change your test in this way:
```
func TestMedianBlur(t *testing.T) {
	// img := IMRead("images/face-detect.jpg", IMReadColor)
	img := IMRead("/Users/pioz/Desktop/sample0.jpg", IMReadColor)
	if img.Empty() {
		t.Error("Invalid read of Mat in MedianBlur test")
	}
	defer img.Close()

	dest := NewMat()
	defer dest.Close()

	MedianBlur(img, &dest, 3)
	if dest.Empty() || img.Rows() != dest.Rows() || img.Cols() != dest.Cols() {
		t.Error("Invalid MedianBlur test")
	}
}
```
The test pass.

But the program `go run medianblur.go /Users/pioz/Desktop/sample0.jpg` still fail with the segmentation violation error.
Really strange.

**Comment by deadprogram** [comment]
I ran your code against the `./images/face-detect.jpg` without any problem on my local machine.

Perhaps you can provide the image you are using for testing?

**Comment by pioz** [comment]
Yes, here my image: https://drive.google.com/open?id=18KQ19tbRthbiZkI4E8XyK8-L1zme_-7x

**Comment by deadprogram** [comment]
Of course it worked perfectly on my machine. I use Ubuntu 16.04.

**Comment by zzzze** [comment]
@deadprogram 

I have the same problem.

I just run the following program in the project root, and get the same result.

`go run ./cmd/find-circles/main.go ./images/circles.jpg`

And I notice that when I change `gocv.MedianBlur(img, &img, 5)` to `gocv.MedianBlur(img, &img, 1)` just the same as it in the unit test, it runs fine. But according to the doc, the `ksize` must be greater than 1.

So, I wonder if there's something wrong with it?

## Environment

Operating System and version: Mac OS X Catalina 10.15.1
OpenCV version used: 4.1.2
How did you install OpenCV? brew install opencv
GoCV version used: 0.21.0
Go version: 1.13.4
Did you run the env.sh or env.cmd script before trying to go run or go build? No

**Comment by deadprogram** [comment]
Any further info on this issue?

**Comment by pioz** [comment]
I think this happens on OSX Catalina.

**Comment by deadprogram** [comment]
I have confirmed this myself on macOS Catalina: https://github.com/opencv/opencv/issues/15964#issuecomment-569250871
